---
language: python

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible

script:
  - cd ../
  - ansible-galaxy init --role-skeleton=ansible-role-skeleton test_role

notifications:
  email: false
